name: CI/CD for lab1_nodeJS

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.1

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test
